#!/bin/bash
[[ -z $DMENU_windownumber ]] && exit
#echo NAME: $DMENU_windowname
newname=$(dmenu $DMENU_ARGS -p "New title:" <<< "$2")
[[ $? == 1 ]] && exit
#echo CHANGING \""$DMENU_windowname"\" to \""$newname"\" number \""$DMENU_windownumber"\"
wmctrl -i -r "$DMENU_windownumber" -N "$newname"
